# docker-compose version
version: '2'
# List of services (containers)
services:
    nginx:
      # use the latest stable nginx image
        image: nginx:latest
        # route ports
        ports:
            - "8000:80"
        # mount directories, on the left are directories on the main machine, on the right - where they are mounted in the container
        volumes:
            - ./hosts:/etc/nginx/conf.d
            - ./www:/var/www
            - ./logs:/var/log/nginx
        # nginx needs to communicate with php container
        links:
            - php
    php:
        # we have our own image for PHP, specify the path to it and say that it needs to be built
        build: ./images/php
        # this image will communicate with mysql
        links:
            - mysql
        # mount the project directory
        volumes:
            - ./www:/var/www
    mysql:
        image: mariadb
        ports:
            - "3306:3306"
        volumes:
            - ./mysql:/var/lib/mysql
        # set password for root user
        environment:
            MYSQL_ROOT_PASSWORD: shgreen-secret
    pma:
        image: phpmyadmin/phpmyadmin
        restart: always
        links:
            - mysql:mysql
        ports:
            - 8183:80
        environment:
            PMA_HOST: mysql
            MYSQL_USERNAME: root
            MYSQL_ROOT_PASSWORD: shgreen-secret
